Uploadifyergram/config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  resources :users
end

Uploadifyergram/app/models/user.rb
class User < ActiveRecord::Base
  has_attached_file :avatar, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  }
  validates :name, presence: true
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/



end

Uploadifyergram/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Uploadifyergram/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    respond_to do |format|
      format.html
      format.json do
        @users = User.all
        render json: @users
      end
    end
  end

  def show
    find_user
  end

  def new
    @user = User.new
  end

  def edit
    find_user
  end

  def create
    @user = User.create(user_params)

    # respond_to do |format|
    #   if @user.save
    #     format.html { redirect_to @user, notice: 'user was successfully created.' }
    #     format.json { render action: 'show', status: :created, location: @user }
    #   else
    #     format.html { render action: 'new' }
    #     format.json { render json: @user.errors, status: :unprocessable_entity }
    #   end
    # end
    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path }
        format.json { render json: {}, status: 201 }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: 422 }
      end
    end
  end

  def update
    find_user
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'user was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    find_user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end


  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :avatar)
  end
end

Uploadifyergram/app/helpers/application_helper.rb
module ApplicationHelper
end

Uploadifyergram/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Uploadifyergram</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>


<h3><%= link_to 'All Users Link', root_path %></h3>


<%= yield %>
</div>



</body>
</html>

Uploadifyergram/app/views/users/_form.html.erb
<%= form_for(@user, multipart: true) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %><br />
  </div>
  <div class="field">
    <%= f.label :avatar %>
    <%= f.file_field :avatar %><br />
  </div>
  <div class="actions">
    <%= f.submit 'Make a user' %>
    <%= link_to 'Nevermind', users_path, class: 'button' %>
  </div>
<% end %>

Uploadifyergram/app/views/users/_user.html.erb
  <div class="user" id="<%= user.id %>">
      <%= link_to user, class: 'pic-link' do %>
      <%= image_tag user.avatar.url(:square) %>
    <% end %>
    <div class="user-name"><%= user.name %></div>
  </div>

  <div>
      <%= link_to 'Show', user_path(user) %>
      <%= link_to 'Edit', edit_user_path(user) %>
      <%= link_to 'Destroy', user_path(user), method: :delete %>
  </div>

Uploadifyergram/app/views/users/edit.html.erb
<h1>Change your peeps*</h1>

<%= render 'form' %>

Uploadifyergram/app/views/users/index.html.erb
<h2>Make a new user <%= link_to 'New user', new_user_path, class: 'new-user' %></h2>

<section id="users">
  <%= render @users %>
</section>

Uploadifyergram/app/views/users/new.html.erb
<h1>Make a new user</h1>

<%= render 'form' %>

Uploadifyergram/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @user.name %></h2>
  <%= image_tag @user.avatar.url(:medium) %>

<h5 class="show actions">
  <%= link_to 'Edit', edit_user_path(@user) %>
  <%= link_to 'Delete', @user, method: :delete, class: 'destroy' %><br />
  <%= link_to 'Back to Peeps', users_path %>
</h5>